### PR TITLE
Added support for mesos 0.23.1

### PR DESCRIPTION
**Pull request by tubit**
I also removed mesos-master and mesos-slave options which are not available in 0.23.0 / 0.23.1 - see #107

### CODE REVIEW

**Comment by dontrebootme** [comment]
Any reason this cant be merged? Would like to have 0.23.1 support seeing as 0.23.0 has issues with the new command health check and is fixed in 0.23.1

**Comment by dontrebootme** [comment]
<3

**Comment by rveznaver** [comment]
Hi @tubit, thank you for your pull request. Could you please check out #115 and tell me what you think?

**Comment by rveznaver** [comment]
Superseded by #115 and #117.

**Pull request closed without merging**
