### PR TITLE
generic templates and no forced uppercase variables

### PR DESCRIPTION
**Pull request by rveznaver**

### CODE REVIEW

**Comment by harryw** [comment]
Thanks @rveznaver. As with #52 I'd like to get @rayrod2030 to review this change as he's been the primary maintainer so far.

**Comment by rayrod2030** [comment]
Thanks for the PR @rveznaver.  This is a nice refactor.  I am in the process of running a bunch of cloud based tests against all versions and supported platforms and if all is well this will good to go.

**Comment by rveznaver** [comment]
@rayrod2030, you're most welcome. As for refactoring, I was thinking of possibly bypassing the mesos-init-wrapper completely and generating the init services with mesos options directly. IMO this 
could vastly simplify the cookbook, get rid of all the Mixin::ShellOuts in the library, and there would be no need for the whole directory structure forced upon by the script. What say you?

**Comment by rayrod2030** [comment]
@harryw @rveznaver Tested against 5x5 matrix of platform and mesos versions.  Looks good.  Found one issue with Centos having a dependency on subversion for mesos 0.21.0+ but it's not related to this PR.  LGTM.  :+1:

**Comment by harryw** [comment]
Thanks both

**Pull request merged**
