### PR TITLE
Update to version 2.1.0 to not conflict with released 2.0.0

### PR DESCRIPTION
**Pull request by barkerd427**

### CODE REVIEW

**Comment by rayrod2030** [comment]
Hey @barkerd427 Thanks for the PR.  We are in the process of moving to 3.0.0 because of all the breaking changes that have been introduced recently.  Once we are at 3.0.0 in supermarket the goal is to respect the versioning scheme and be very careful with breaking changes that are not backward compatible.  Look for 3.0.0 to land some time today.  Read here for details: https://github.com/mdsol/mesos_cookbook/issues/62

**Comment by barkerd427** [comment]
@rayrod2030, the only thing I'm trying to address is that there's a tagged 2.0.0 version, so this one won't upload to a Chef Server if the released version is already frozen on there. We can certainly move the version to 3.0.0 instead due to the large changes. I've had to fork this to take the changes I need. Also, the updates are awesome!

**Comment by rayrod2030** [comment]
Yeah totally understand.  I'll merge your PR to make the latest stuff usable post 2.0.0 and will do an official release to 3.0.0 soon.  Thanks!

**Comment by barkerd427** [comment]
Thanks, Ray.

**Pull request merged**
