### PR TITLE
Export shell variables

### PR DESCRIPTION
**Pull request by cdegroot**
This allows passing of settings like DOCKER_CONFIG through to
spawned docker processes.

### CODE REVIEW

**Comment by rveznaver** [comment]
How is this different than using the ```--executor_environment_variables=VALUE``` option to pass ENV variables to the executor?

**Comment by cdegroot** [comment]
This is simpler? ;)

**Comment by rveznaver** [comment]
The only reason why we have those env variables in the first place is because of the ulimit.

And the difference between:
```default['mesos']['slave']['flags']['env']['DOCKER_CONFIG'] = 'whatever'```
and 
```default['mesos']['slave']['flags']['executor_environment_variables'] = 'DOCKER_CONFIG' => 'whatever' ```
is not that big.

**Comment by cdegroot** [comment]
You got a point there. I wasn't aware of this option (the list is so long). Will give it a shot next week and then close this.

**Pull request closed without merging**
