### PR TITLE
Add switch for default cookbook repository

### PR DESCRIPTION
**Pull request by rveznaver**
If someone would like to mirror the mesosphere repository on their own infrastructure, or have their own packages, one should be able to disable the default mesosphere repository.

### CODE REVIEW

**Comment by rayrod2030** [comment]
This looks good and is probably a much better alternative to both installing a custom built binary and/or compiling from source from within the cookbook as I had brought up as possible features.  Makes sense that most places running Mesos in production would choose to pre-build and pre-package (deb/rpm) their custom Mesos builds.  Running this through integration tests now.  Have you been able to try this out with a custom package repo?

**Comment by rayrod2030** [comment]
This change fails all centos based integration tests as it looks like 0.22.0 is being installed regardless of what mesos  version is set via the cookbook attributes.  I'm guessing this is due to changes in the way we search for and install specific mesos versions from the mesosphere RPM repo.  These are the failing suites:

* default-centos-64
* attributes-centos-64
* 0-21-0-centos-64
* 0-20-1-centos-64
* 0-20-0-centos-64

**Comment by rveznaver** [comment]
Have not been able to test it with a custom repo yet, but I'm pretty sure it will work with our use case (a wrapper cookbook).

**Comment by rveznaver** [comment]
The yum_package provider did not handle the version attribute correctly (meaning: at all) before Chef 2.1.0. The kitchen.yml tests are set to "require_chef_omnibus: 12.0.3". I've done a test with the newest chef version and it works. Maybe we should set a newer chef version?

**Comment by rayrod2030** [comment]
I am testing against chef 12.1.2 and still see the issues.

**Comment by rveznaver** [comment]
Hi @rayrod2030, you're right. The yum_package provider does not support passing a ruby block to the version. I have patched and rebased. Should be fine now.

**Comment by rayrod2030** [comment]
All integration tests passed.  Merging!

**Pull request merged**
