### PR TITLE
Get rpm version from Chef yum cache

### PR DESCRIPTION
**Pull request by rveznaver**
This is a first step towards #87. Also removes dependency on yum-utils.

### CODE REVIEW

**Comment by rayrod2030** [comment]
Nice thanks!

**Comment by ronlipke** [comment]
I'm having an issue with this that I can't pin down.  
I have ['mesos']['version'] set as a default attribute in an environment file, but on initial chef-client run, it's blank, which causes the run to fail on `undefined method 'find' for nil:NilClass`.  Re-running the chef-client and everythings is fine.
I've testing move the attribute to override and setting in the wrapper cookbook directly, but doesn't have any effect.

**Comment by rveznaver** [comment]
@ronlipke This is weird. We are setting up the version in a wrapper cookbook as well and it works fine. What version of Chef are you running?

**Comment by ronlipke** [comment]
Sorry for the long delay.  I'm having this issue with Chef 12.4.2 and 12.5.1 on Centos 7.1 and it only occurs when I have our base cookbook in the runlist before mesos.  The recipes that get run before `mesos::repo` in this case are `build_essential::_rhel`, `xml::default` and `xml::ruby`, plus a few chef_gem resources.
Makes me think it's not the version attribute, but the yum cache.  Will troubleshoot a little further when I get a chance.

**Pull request merged**
