### PR TITLE
Improve package management

### PR DESCRIPTION
**Pull request by kamaradclimber**
This patch improves package management:
- it stop using dynamic version computation for rhel. This creates non-deterministc behavior
- it allows to pass options to package (convenient when using custom repositories for instance)

cc @criteo-cookbooks/sre-core

### CODE REVIEW

**Comment by rveznaver** [comment]
Please elaborate on point (1). AFAIK, due to a missing feature in the yum package provider, it behaves differently from dpkg (the version must be specified fully, it does not support wildcards for the release part). Has this been fixed in a recent Chef version? If so, which one?

Also, please fix tests in Travis.

**Comment by kamaradclimber** [comment]
Thanks for the feedback.

un-deterministic behavior comes from the fact that dynamic version will upgrade mesos package to latest version available (instead of offering full control to user via attributes).
Indeed yum_package resource does not offer the same level of customization as apt_package (but this is a behavior of apt itself).

I'll have a look at travis

**Comment by kamaradclimber** [comment]
fixed all issues @rveznaver  :)

**Comment by kamaradclimber** [comment]
any news @rveznaver ?

**Comment by rveznaver** [comment]
I have yet to review and test this change. Should have some time next week. Sry.

**Comment by kamaradclimber** [comment]
Any news @rveznaver ?

**Comment by clems4ever** [comment]
I also had a look at it and it looks good to me!

**Comment by kamaradclimber** [comment]
closing since #149 has no answer at all

**Pull request closed without merging**
