### PR TITLE
Dynamic configuration guard

### PR DESCRIPTION
**Pull request by rveznaver**
Instead of writing all possible options in a static attribute file, this PR proposes a new mechanism where all possible options are extracted from the command's "--help" output (at converge time) and checked against the given attributes. In case of an unsupported option, the Chef run will fail before modifying any configuration option for Mesos.

This should enable support for any Mesos version without modifying the cookbook's attribute file every single time a new version comes out.

### CODE REVIEW

**Comment by pierrecdn** [comment]
Nice ! LGTM :+1:

**Comment by FlorentFlament** [comment]
+1

**Comment by tubit** [comment]
Nice one. :+1:

**Comment by rveznaver** [comment]
Thanks, waiting for a go from @rayrod2030 on this one as it changes the logic quite a bit.

**Comment by rayrod2030** [comment]
Will review today.

**Pull request merged**
