### PR TITLE
Add 0.22.0 to options list.

### PR DESCRIPTION
**Pull request by ankurcha**

### CODE REVIEW

**Comment by rayrod2030** [comment]
Hey @ankurcha Thanks for the PR.  Luckily I have been working on this same thing and have a PR almost ready to go as I'm putting it through it's final testing.  It includes most of what you have done here with the attributes plus some additional changes that are needed for this cookbook to work with 0.22.0.  Thanks for your contribution!

**Comment by rayrod2030** [comment]
Oh and yeah we should have a 0.22.0 compatible cookbook by end of day once all the test suites pass.

**Comment by rayrod2030** [comment]
Here is the 0.22.0 pull request if you want to give feedback and/or comment on it https://github.com/mdsol/mesos_cookbook/pull/79

**Comment by ankurcha** [comment]
Thanks closing this PR in favor of #79

**Pull request closed without merging**
